### ISSUE TITLE
demo 文档支持自定义 HTML

### ISSUE THREAD

**Issue by axuebin** [ice-lab/iceworks-cli#114]
buid-plugin-component 的 demo 文档支持自定义 HTML，而不是通过插件的形式去加载一些静态资源文件。

主要是因为有时候一个组件需要一些开发环境，比如 dom，前置 js，reset.css 等

**Comment by imsobear** [comment]
![image](https://user-images.githubusercontent.com/2505411/105164273-e7892180-5b4f-11eb-96ed-b8edc8f0548e.png)

**Comment by axuebin** [comment]
get
