### ISSUE TITLE
rax 组件demo 支持引入 css 和 js

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/iceworks-cli#115]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

**Comment by imsobear** [comment]
同类问题 #157
