### ISSUE TITLE
引入外部样式报错

### ISSUE THREAD

**Issue by RiderGj** [ice-lab/iceworks-cli#128]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
在demo里引入外部css，我试了在demo/usage.md和src/index.tsx里引都会报错找不到该文件，应该是用的同一个miniapp-compile生成的小程序dsl
引入方式：
![image](https://user-images.githubusercontent.com/23232713/107143327-7333e800-696f-11eb-8a97-c88c4dcf278c.png)
问题：
这里的rax-herbox-usage.acss已经导入样式了，但是rax-herbox-usage.js里还有这条import，所以找不到
![image](https://user-images.githubusercontent.com/23232713/107143340-88107b80-696f-11eb-8740-5e08165ca0cf.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**
预期可以引入样式

**Comment by ChrisCindy** [comment]
https://github.com/raxjs/miniapp/pull/90

**Comment by ChrisCindy** [comment]
fixed
