### ISSUE TITLE
请教下开发Rax组件为啥不支持 htmlInjection配置，只有开发React组件可以？

### ISSUE THREAD

**Issue by inX95** [ice-lab/iceworks-cli#144]
RT。
看源码rax组件没有读取HTMLInjection配置，https://github.com/ice-lab/iceworks-cli/blob/master/packages/build-plugin-component/src/rax.js

**Comment by imsobear** [comment]
具体有什么诉求~~

**Comment by maoxiaoke** [comment]
移步 https://github.com/ice-lab/iceworks-cli/issues/157
