### ISSUE TITLE
build-plugin-component 对于 externals 的支持

### ISSUE THREAD

**Issue by liunian** [ice-lab/iceworks-cli#153]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

`A`  组件使用了 `@alifd/next`，使用 `build-plugin-componet` 发布 npm 包，默认会把 fusion 的 import 替换为 `const button = require('@alifd/next/es/button')` 之类的形式。

`B` 组件使用了 `A` 组件，希望把 `@alifd/next` externals 掉，构建 `umd` 版本，实际构建产物中，包含 `@alifd/next` 的 js 以及 css。

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

希望 B 在配置了 `externals` 后，umd 构建产物中，对于 B 依赖中的其它组件中的 `@alifd/next` 也能 external 掉。

* Iceworks CLI version：3.2.0
* Node verson：12.14.1
* Platform：macOS Big Sur 11.2.3

**What is the expected behavior?**

**Comment by ClarkXia** [comment]
## 组件打包方式

策略一：不处理基础依赖组件的分包模式，即组件内部为 `import  { Button } from '@alifd/next';` 编译之后保持不变
策略二：默认处理按需引入，`import  { Button } from '@alifd/next';`  编译后将转化为 `import  Button from '@alifd/next/es/Button';`

策略一在项目开发过程中需要全量编译 node_modules，目前来看将会大大降低研发体验，因此目前 ice 组件工程采用策略二的方式对组件进行编译

## 将 Next 组件库作为外部依赖

通过策略一的方式可以简单设置 `externals: { '@alifd/next': 'Next'}` 即可
策略二需要通过配置 function 类型的 externals 逻辑将分包后的引入进行处理，具体逻辑参考 [build-plugin-fusion](https://github.com/alibaba/ice/blob/master/packages/plugin-fusion/src/index.js#L323)

在 ice 项目开发体系下，可以配置插件的方式完成 externals 的[配置](https://ice.work/docs/guide/advance/fusion#%E9%85%8D%E7%BD%AE%20externals)

## umd 打包

一般情况下，umd 产物需要配置 externals next 时，可以直接在 build.json 中配置，默认 externals 逻辑已包含 react、react-dom、@alifd/next 和 moment 的配置。
如果该组件又依赖了由上述策略二打包的组件，在构建时将无法将分包后的引入组件，作为外部依赖进行移除。因此需要提供类似 build-plugin-fusion 中 externalNext 的能力

>  关于 build-plugin-fusion 中 externalNext 能力为什么不直接对 umd 生效的问题：
> build-plugin-fusion 引入后，定位上希望只对组件 demo 的任务生效，umd 构建配置和 demo 构建配置应该相互独立

## 优化方案

组件配置上结合 basicComponents 和 externals 配置，共同决定 externals 规则。
```json
{
  "externals": {
    "@alifd/next": "Next",
    "antd": "Antd"
  },
  "basicComponent": ["antd", "@alifd/next"],
  "plugins": ["build-plugin-component"]
}
```

 在上述配置的场景下，需要默认添加 function 形式的 externals 规则，实现方式类似 build-plugin-fusion 中 externalNext 逻辑。用户在配置层面不需要关系底层的组件依赖是否发生分包

> 默认逻辑：
> basicComponent 目前的默认只包含 @alifd/next，因此基于 Next 组件体系开发，仅需配置 externals

build-plugin-fusion 的 externals 逻辑同样需要进行类似配置优化，自动检测 externals 是否包含 @alifd/next 相关规则，来构造 externals 函数

cc @maoxiaoke @imsobear
