### ISSUE TITLE
业务组件 API 内容后置展示

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/iceworks-cli#18]
![image](https://user-images.githubusercontent.com/4219965/91002764-2e570780-e602-11ea-92f6-0b25370156df.png)

API 说明一般会放在在 README 中，而展示上希望优先显示组件 DEMO 和示例代码

**Comment by ClarkXia** [comment]
同步考虑组件 CHANGELOG 展示需求

**Comment by imsobear** [comment]
重复问题：https://github.com/ice-lab/iceworks-cli/issues/105
