### ISSUE TITLE
Bug(build-plugin-component): throw error when build set `define` option in build.json

### ISSUE THREAD

**Issue by love2me** [ice-lab/iceworks-cli#235]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
it will cause error when run build and set `define` option in build.json, but i found a PR https://github.com/ice-lab/iceworks-cli/pull/217 for supporting this option.
![image](https://user-images.githubusercontent.com/25655387/140046157-0e3638d8-c417-412b-92f4-e96f83b2f8bc.png)

![image](https://user-images.githubusercontent.com/25655387/140045388-49768c38-c623-4222-a2a1-b2362a3a7ae9.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
- reproduce repo: https://github.com/love2me/build-plugin-component-define-test
- reproduce step: clone the repo, run `yarn && yarn build` command

* Iceworks CLI version：build-plugin-component@^1.0.0、 build-scripts@^1.1.1
* Node verson：v12.22.7
* Platform：macos

**What is the expected behavior?**
build success and the `define` option will take effect

**Comment by maoxiaoke** [comment]
`define` is valid with `type: react` currently.

**Comment by maoxiaoke** [comment]
A [beta version](https://www.npmjs.com/package/build-plugin-component/v/1.8.1-0) was published to make `define` work with `type: rax`, and you can have a try. I will publish it as soon as possible.

Try to install as followed: 

```shell
npm i build-plugin-component@1.8.1-0
```

**Comment by love2me** [comment]
> A [beta version](https://www.npmjs.com/package/build-plugin-component/v/1.8.1-0) was published to make `define` work with `type: rax`, and you can have a try. I will publish it as soon as possible.
> 
> Try to install as followed:
> 
> ```shell
> npm i build-plugin-component@1.8.1-0
> ```

Thx, the beta version has worked, looking forward to the stable version soon.
