### ISSUE TITLE
业务组件开发支持 rax

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/iceworks-cli#25]
## React / Rax 组件构建核心差异

React 组件开发定制逻辑：
- 分析基础依赖，按需打包，对应配置项 basicComponents
- 组件构建默认生成 style.js
- 使用 @babel/preset-typescript 编译 ts 文件（tsconfig.json 无效）
- 定制 demo 样式和解析逻辑

Rax 组件开发定制逻辑：
- 支持 miniapp / wechat-miniprogram 小程序内容生成
- weex 相关 bundle 输出
- forceInline 内联样式处理
- ssr 构建逻辑
- 通过 gulp 调用 ts 进行编译
- 插件支持 demo

## 插件合并待处理问题

- [x] react 组件构建配置依赖 build-scripts-config，rax 依赖 rax-babel-config / rax-compile-config，不同 targets 下会有不同基础 webpack 配置
- [x] react demo 会有大量默认样式及定制 md 书写规范；rax 默认启动 demo 目录下内容（md/js），通过插件支持额外 demo 样式
- [x] 组件相关配置统一，比如默认 rax 特有 targets，react 特有 basicComponents；区分构建类型
- [x] ts 编译逻辑统一
- [x] externals 规则各自维护

**Comment by imsobear** [comment]
build-plugin-component@1.0.0 已发布
