### ISSUE TITLE
组件 Demo 预览支持大包和编辑器

### ISSUE THREAD

**Issue by axuebin** [ice-lab/iceworks-cli#26]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

无.

**What is the expected behavior?**

- 大包组件：小组件列表+小组件内部 TOC
- 编辑器：支持 demo 在线编辑预览

比如：https://opendocs.alipay.com/mini/component/text

看到相关的 issue：

- https://github.com/ice-lab/iceworks-cli/issues/14
- https://github.com/ice-lab/iceworks-cli/issues/22

这里统一提一下

**Comment by imsobear** [comment]
build-plugin-component@1.0.0 已发布
