### ISSUE TITLE
组件 externals @alifd/next 不生效

### ISSUE THREAD

**Issue by axuebin** [ice-lab/iceworks-cli#27]
## 现象

使用 `build-plugin-compoent` + `build-plugin-fusion` 时，externals @alifd/next 无效。

组件代码：

```jsx
import React from 'react';
import { Rating } from '@alifd/next';

export default function Comp() {
  return (
    <div>
      <Rating defaultValue={3.2} onChange={val => console.log('change:', val)} onHoverChange={val => console.log('hover:', val)} />
    </div>
  );
}
```

构建结果：

![image](https://user-images.githubusercontent.com/13316392/91927412-06eff100-ed0c-11ea-8454-94817dd57cc0.png)

我看 `build-plugin-compoent`  是有默认的 `externals : { "@alifd/next" : ... }` 的。

应该是由于 `build-plugin-fusion` 里引入了 `babel-plugin-import` 的原因？

```javascript
import { Rating } from '@alifd/next';

// =>

import Rating from '@alifd/next/lib/rating';
```

所以 `externals` 没匹配上？

## 期望

期望组件可以把整个 `@alifd/next` external 出去，使用挂载在 window 上的 Next。当然，理论上我可以这样：

```jsx
import Rating from '@alifd/next/lib/rating';
```

```json
{
  "externals": {
    "@alifd/next/lib/rating": "root Next.rating"
  }
}
```

但是组件多了就比较麻烦。

所以想问一下，在需要使用 `build-plugin-fusion` 并且按需加载的情况下有没有什么解决方案。

`build-plugin-component` 内置的 `@alifd/next` 貌似也必要了。

**Comment by ClarkXia** [comment]
看下这个方案：https://ice.work/docs/guide/advance/fusion#%E9%85%8D%E7%BD%AE%E5%A4%96%E9%83%A8%E6%89%A9%E5%B1%95%EF%BC%88externals%EF%BC%89

**Comment by axuebin** [comment]
> 看下这个方案：https://ice.work/docs/guide/advance/fusion#%E9%85%8D%E7%BD%AE%E5%A4%96%E9%83%A8%E6%89%A9%E5%B1%95%EF%BC%88externals%EF%BC%89

OK 🉑
