### ISSUE TITLE
generate-project 支持定制

### ISSUE THREAD

**Issue by imsobear** [ice-lab/iceworks-cli#31]
- abc.json 不覆盖
- package.json 的字段特殊处理

**Comment by imsobear** [comment]
定制方案：

scaffold 的 package.json 里新增 bizTeam 字段，generator 根据这个字段做特殊性处理，生成项目的时候会删除该字段，防止用户困扰。

如需定制，请按下面的格式回复 issue：

- bizTeam: "x-team"
- 定制逻辑：不要追加 private 字段

**Comment by xiazhiqiang** [comment]
> 定制方案：
> 
> scaffold 的 package.json 里新增 bizTeam 字段，generator 根据这个字段做特殊性处理，生成项目的时候会删除该字段，防止用户困扰。
> 
> 如需定制，请按下面的格式回复 issue：
> 
> * bizTeam: "tb"，淘系前端团队
> * 定制逻辑：不要追加 private 字段

bizTeam: "govfe",  政务中台前端团队
定制逻辑：
1）abc.json不覆盖
2）package.json 不追加private字段，devDependency不包括集团def构架插件
3）build.json 去掉def构建插件
4）能否支持inquire的配置问答文件，在init执行时读取让用户选择，然后把选择的值替换模板中的变量写法

**Comment by imsobear** [comment]
4) 只能支持通用的选项，不会支持个性化。

通用选项目前 Rax 有几个，ICE 的还没有，有需求可以先提：https://github.com/ice-lab/iceworks-cli/blob/master/packages/generate-project/src/index.ts#L14
