### ISSUE TITLE
业务组件构建样式产物规范

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/iceworks-cli#36]
## 背景

为了解决组件的样式加载问题，同时为了隔离脚本和样式，目前业务组件自身样式以及依赖基础组件的样式我们会单独构建一个 style.js 的文件：

```js
require('@alifd/next/lib/form/style');
require('@alifd/next/lib/button/style');
require('@icedesign/balloon-confirm/lib/style');
require('./index.scss');
```

并且默认将基础组件按需进行加载。
上述逻辑对于在项目层面对基础依赖进行 externals 处理时会变得比较困难。因此希望能通过简化构建逻辑，由项目工程决定业务组件中样式的加载以及按需逻辑。

## 方案
业务组件构建不再按需进行分析和 style.js 文件的生成，在项目中进行依赖时，webpack 插件自动加载的 `style.js` 文件变更为 `index.[css|sass|less]` 文件。

## 问题
目前 ice 项目工程 babel 编译默认忽略 node_modules，业务组件如果想开启按需加载 `babel-plugin-import` 等 babel 编译能力，需要对 node_modules 下目录进行编译，一定程度上影响编译速度

**Comment by maoxiaoke** [comment]
已完成
