### ISSUE TITLE
为什么这里是inline-block

### ISSUE THREAD

**Issue by ylfeng250** [ice-lab/iceworks-cli#42]
https://github.com/ice-lab/iceworks-cli/blob/b31a9240ff9d135c065851807655b5006aa9216c/packages/template-component-demo/src/Playground/CodeBox.jsx#L27

设置 inline-block就要求在编写demo的时候去设置宽度把盒子撑开，是不是保持block更合理一些。或者可以回复一下这里设置inline-block的考虑是什么

**Comment by ClarkXia** [comment]
为了让截图的时候只显示组件区域，目前已移除该样式，截图插件中将优化相关问题
