### ISSUE TITLE
build-plugin-component构建时加载字体，用相对路径引用时打包报错

### ISSUE THREAD

**Issue by minzhang2** [ice-lab/iceworks-cli#43]
build-plugin-component构建时加载字体，用相对路径引用时打包报错
![image](https://user-images.githubusercontent.com/15793061/97558706-70903100-1a17-11eb-935e-dbf3d1e5470d.png)

上面是相对地址方式加载不到，换成绝对地址能加载到，绝对地址是临时用的

**Comment by imsobear** [comment]
下周一我们评估下

**Comment by ClarkXia** [comment]
资源路径使用相对地址即可，组件构建的时候不会对样式文件进行编译。具体的样式的打包会在项目工程层面处理
