### ISSUE TITLE
组件开发 rax demo 的样式问题

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/iceworks-cli#44]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

rax 组件开发在 markdown 中添加 css 内容后，样式注入在入口（portal 页面）

**What is the expected behavior?**

样式注入到具体的 demo 页面中

**Comment by axuebin** [comment]
是否可以通过 scss 样式引入， 在 demo 里 `import './indes.scss';` 这样
