### ISSUE TITLE
组件 demo 支持引入 css 和 js 脚本

### ISSUE THREAD

**Issue by ClarkXia** [ice-lab/iceworks-cli#54]
一些组件 demo 依赖 第三方样式或者脚本需要支持对应链接的引入
目前方案通过在 [build-plugin-load-assets 的方案](https://ice.work/docs/guide/develop/plugin-list#plugin-load-assets) 对组件umd 开发构建结果会产生影响，需要一个更加简单的方式添加资源

**Comment by imsobear** [comment]
本质是定制 html 的内容，看看能不能支持如下配置：

![Uploading image.png…]()

**Comment by imsobear** [comment]
@zuoqi705 下周发布
