### ISSUE TITLE
Bug: Portal 预览窗口在demo过宽时被挤压

### ISSUE THREAD

**Issue by cytle** [ice-lab/iceworks-cli#61]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**

![image](https://user-images.githubusercontent.com/5120505/100577472-47670700-331b-11eb-9e1e-cd505fbcdc04.png)

Portal 预览窗口未设置flex宽度被挤压

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

**Comment by ClarkXia** [comment]
demo 样式已修复
