### ISSUE TITLE
Bug: build-plugin-component 升级后无法使用 fusion 主题基础变量

### ISSUE THREAD

**Issue by Suixinlei** [ice-lab/iceworks-cli#70]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

升级 build-plugin-component 后无法使用 fusion 基础变量
![image](https://user-images.githubusercontent.com/5600924/101860686-4a7ab680-3ba9-11eb-9e6f-896d7499b62d.png)
![image](https://user-images.githubusercontent.com/5600924/101860697-4fd80100-3ba9-11eb-8d86-b831534c0e67.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：0.1.30
* Node verson：13.12.0
* Platform：mac

**What is the expected behavior?**

需要能够使用 fusion 变量

**Comment by ClarkXia** [comment]
fusion 插件目前对于 dist 构建是失效的，dist 最终构建结果是 css，如果想直接使用主题需要手动将主题的 variables 添加进来
