### ISSUE TITLE
组件可控制样式打包方式

### ISSUE THREAD

**Issue by jzlingmo** [ice-lab/iceworks-cli#74]
## 背景
组件包中同时包含了多个插件模块，且每个模块中会使用antd或antd-mobile等ui库
```ts
src
-- plugins
---- A.js
---- B.js
-- index.js
```

可直接使用当前依赖包按需引入
```ts
import A from 'x/lib/plugins/A';
import B from 'x/lib/plugins/B';
import X from 'x';

X.add(A);
X.add(B);
```

## 问题
目前的情况，输出lib和es结果时，babel-plugin-import配置style为false，在后续解析依赖统一生成到style.js
因此，上述场景下，由于X并没有直接引入A、B，A、B模块antd相关的样式会丢失

## 方案
希望可以提供style配置项自由控制，`style: true`且不生成style.js

**Comment by maoxiaoke** [comment]
配置 `disableGenerateStyle: true`，不再生成 style.js
