### ISSUE TITLE
demo 目录下的 basic.md 为空的时候，不展示 Demo

### ISSUE THREAD

**Issue by tanyafuzhou** [ice-lab/iceworks-cli#77]
demo 目录下的 basic.md 为空的时候，可以不展示红框中的内容
![image](https://user-images.githubusercontent.com/7301604/102196578-0e25be00-3efb-11eb-91f6-dbb0a2fb8428.png)

![image](https://user-images.githubusercontent.com/7301604/102196562-06feb000-3efb-11eb-98dc-1f46e47b4459.png)

**Comment by maoxiaoke** [comment]
@tanyafuzhou build.json 的是什么，尝试增加或修改
```json
{
  "type": "react"
}
```
