### ISSUE TITLE
物料脚手架期望支持大包场景

### ISSUE THREAD

**Issue by orangeyyy** [ice-lab/iceworks-cli#8]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
目前ice提供的脚手架只支持一个包一个业务组件，但是有些场景希望将组件放在一个大包里面，例如Fusion和Antd，因此希望ice脚手架能够支持大包组件库场景(每个组件的readme和demo独立在当前组件的文件夹内)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**

**Comment by imsobear** [comment]
业务场景较少，iceworks CLI 层面暂时不考虑支持这个场景
