### ISSUE TITLE
inlineStyle 设置为 true 时，less 嵌套写法不生效

### ISSUE THREAD

**Issue by maoxiaoke** [ice-lab/iceworks-cli#85]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

```jsx
import { createElement } from 'rax';
import View from 'rax-view';
import Text from 'rax-text';

import './index.less';

const MyComponent = () => {
  return (
    <View className="test">
      <Text className="test-a">放松放松</Text>
    </View>
  );
};


export default MyComponent;

```

```less
.test {
  background-color: red;

  .test-a {
    color: yellow;
  }
}
````

![image](https://user-images.githubusercontent.com/13417006/102474432-963ecb80-4093-11eb-8c3c-9bf4233fb576.png)

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

* Iceworks CLI version：
* Node verson：
* Platform：

**What is the expected behavior?**
支持 less 嵌套写法

**Comment by imsobear** [comment]
这个是符合预期的，支持的优先级不太高

**Comment by imsobear** [comment]
`<View className="test_test-a" />`
